import {
  frameworkResourceSpecSchema,
  type FrameworkResourceSpec
} from "../../packages/framework/src/index.js";

export interface GeneratedProductResource {
  listPath: string;
  navLabel: string;
  resource: FrameworkResourceSpec;
}

export interface GeneratedProductSpec {
  description?: string;
  home?: {
    ctaLabel?: string;
    description: string;
    title: string;
  };
  id: string;
  name: string;
  resources: readonly GeneratedProductResource[];
}

export function readGeneratedProductSpec(value: unknown): GeneratedProductSpec {
  if (!isObject(value)) {
    throw new Error("Generated product spec must be a JSON object.");
  }

  const id = readNonEmptyString(value.id, "id");
  const name = readNonEmptyString(value.name, "name");
  const description = readOptionalNonEmptyString(value.description, "description");
  const home = readHome(value.home);
  const resourcesValue = value.resources;

  if (!Array.isArray(resourcesValue) || resourcesValue.length === 0) {
    throw new Error("Generated product spec must include at least one resource.");
  }

  const resources = resourcesValue.map((resourceEntry, index) =>
    readGeneratedProductResource(resourceEntry, index)
  );
  const seenResourceIds = new Set<string>();
  const seenPaths = new Set<string>();

  for (const resourceEntry of resources) {
    if (seenResourceIds.has(resourceEntry.resource.resource)) {
      throw new Error(
        `Generated product spec contains duplicate resource '${resourceEntry.resource.resource}'.`
      );
    }

    if (seenPaths.has(resourceEntry.listPath)) {
      throw new Error(
        `Generated product spec contains duplicate route '${resourceEntry.listPath}'.`
      );
    }

    seenResourceIds.add(resourceEntry.resource.resource);
    seenPaths.add(resourceEntry.listPath);
  }

  return {
    description,
    home,
    id: readProductId(id),
    name,
    resources
  };
}

export function createTodoProductSpec(input: {
  description?: string;
  productId: string;
  productName: string;
}) {
  const resource = normalizeTodoResource(input.productId);

  return readGeneratedProductSpec({
    description:
      input.description ??
      `${input.productName} is a simple resource-backed workspace product generated by Elioric.`,
    home: {
      ctaLabel: `Open ${resource.pluralLabel}`,
      description: `Track work through one generated ${resource.label.toLowerCase()} resource without hand-editing product runtime seams.`,
      title: `${input.productName} workspace`
    },
    id: input.productId,
    name: input.productName,
    resources: [
      {
        listPath: `/${input.productId}/${pluralizePathSegment(toKebabCase(resource.resource))}`,
        navLabel: resource.pluralLabel,
        resource
      }
    ]
  });
}

export function createCrmProductSpec(input: {
  description?: string;
  productId: string;
  productName: string;
}) {
  const resources = createCrmResources(input.productId);

  return readGeneratedProductSpec({
    description:
      input.description ??
      `${input.productName} is a generated CRM workspace product for tracking companies, contacts, deals, and notes through Elioric's reusable product seams.`,
    home: {
      ctaLabel: "Open Deals",
      description:
        "Manage companies, contacts, deals, and notes through one generated multi-resource CRM workspace without hand-editing shared runtime seams.",
      title: `${input.productName} workspace`
    },
    id: input.productId,
    name: input.productName,
    resources: resources.map((resource) => ({
      listPath: `/${input.productId}/${pluralizePathSegment(toKebabCase(resource.resource))}`,
      navLabel: resource.pluralLabel,
      resource
    }))
  });
}

function readGeneratedProductResource(value: unknown, index: number): GeneratedProductResource {
  if (!isObject(value)) {
    throw new Error(`Generated product resource at index ${index} must be an object.`);
  }

  return {
    listPath: readNonEmptyString(value.listPath, `resources[${index}].listPath`),
    navLabel: readNonEmptyString(value.navLabel, `resources[${index}].navLabel`),
    resource: frameworkResourceSpecSchema.parse(value.resource)
  };
}

function readHome(value: unknown) {
  if (value === undefined) {
    return undefined;
  }

  if (!isObject(value)) {
    throw new Error("Generated product home config must be an object.");
  }

  return {
    ctaLabel: readOptionalNonEmptyString(value.ctaLabel, "home.ctaLabel"),
    description: readNonEmptyString(value.description, "home.description"),
    title: readNonEmptyString(value.title, "home.title")
  };
}

function normalizeTodoResource(productId: string): FrameworkResourceSpec {
  const resourceId = singularizeProductId(productId);
  const pluralPath = pluralizePathSegment(toKebabCase(resourceId));

  return frameworkResourceSpecSchema.parse({
    api: {
      filters: [],
      pagination: true,
      prefix: `/v1/organizations/:organizationId/${pluralPath}`,
      public: false
    },
    archive: {
      enabled: true,
      field: "archivedAt"
    },
    crud: {
      create: true,
      delete: false,
      list: true,
      read: true,
      update: true
    },
    fields: [
      {
        name: "title",
        required: true,
        searchable: true,
        sortable: true,
        type: "string"
      },
      {
        name: "details",
        required: false,
        type: "text"
      },
      {
        default: "todo",
        name: "status",
        required: true,
        type: "enum",
        values: ["todo", "done"]
      },
      {
        name: "dueAt",
        required: false,
        type: "datetime"
      }
    ],
    label: toTitleCase(resourceId),
    ownership: "organization",
    permissions: {},
    pluralLabel: pluralizeLabel(toTitleCase(resourceId)),
    relations: [],
    resource: resourceId,
    timestamps: {
      createdAtField: "createdAt",
      enabled: true,
      updatedAtField: "updatedAt"
    },
    ui: {
      createPage: false,
      detailPage: false,
      editPage: false,
      listPage: false,
      nav: false,
      navLabel: pluralizeLabel(toTitleCase(resourceId))
    }
  });
}

function createCrmResources(productId: string): FrameworkResourceSpec[] {
  return [
    normalizeProductResource({
      fields: [
        {
          name: "name",
          required: true,
          searchable: true,
          sortable: true,
          type: "string"
        },
        {
          name: "domain",
          required: false,
          searchable: true,
          sortable: true,
          type: "string"
        },
        {
          default: "lead",
          name: "status",
          required: true,
          type: "enum",
          values: ["lead", "customer", "inactive"]
        }
      ],
      label: "Company",
      resourceId: "company"
    }),
    normalizeProductResource({
      fields: [
        {
          name: "name",
          required: true,
          searchable: true,
          sortable: true,
          type: "string"
        },
        {
          name: "email",
          required: false,
          searchable: true,
          sortable: true,
          type: "email"
        },
        {
          name: "title",
          required: false,
          searchable: true,
          sortable: true,
          type: "string"
        }
      ],
      label: "Contact",
      relations: [
        {
          kind: "belongs-to",
          name: "company",
          required: true,
          target: "company",
          targetScope: "generated"
        }
      ],
      resourceId: "contact"
    }),
    normalizeProductResource({
      fields: [
        {
          name: "name",
          required: true,
          searchable: true,
          sortable: true,
          type: "string"
        },
        {
          default: "lead",
          name: "stage",
          required: true,
          type: "enum",
          values: ["lead", "qualified", "proposal", "won", "lost"]
        },
        {
          name: "amount",
          required: false,
          sortable: true,
          type: "string"
        }
      ],
      label: "Deal",
      policy: {
        archive: {
          mode: "ownership-aware",
          ownerField: "ownerId"
        },
        read: {
          mode: "ownership-aware",
          ownerField: "ownerId"
        },
        workflow: {
          mode: "ownership-aware",
          ownerField: "ownerId"
        },
        write: {
          mode: "ownership-aware",
          ownerField: "ownerId"
        }
      },
      relations: [
        {
          kind: "belongs-to",
          name: "company",
          required: true,
          target: "company",
          targetScope: "generated"
        },
        {
          kind: "belongs-to",
          name: "owner",
          required: false,
          target: "user",
          targetScope: "platform"
        }
      ],
      resourceId: "deal"
    }),
    normalizeProductResource({
      fields: [
        {
          name: "body",
          required: true,
          searchable: true,
          type: "text"
        }
      ],
      label: "Note",
      relations: [
        {
          kind: "belongs-to",
          name: "deal",
          required: true,
          target: "deal",
          targetScope: "generated"
        }
      ],
      resourceId: "note"
    })
  ];
}

function normalizeProductResource(input: {
  fields: NonNullable<FrameworkResourceSpec["fields"]>;
  label: string;
  policy?: FrameworkResourceSpec["policy"];
  relations?: NonNullable<FrameworkResourceSpec["relations"]>;
  resourceId: string;
}) {
  const pluralPath = pluralizePathSegment(toKebabCase(input.resourceId));

  return frameworkResourceSpecSchema.parse({
    api: {
      filters: [],
      pagination: true,
      prefix: `/v1/organizations/:organizationId/${pluralPath}`,
      public: false
    },
    archive: {
      enabled: true,
      field: "archivedAt"
    },
    crud: {
      create: true,
      delete: false,
      list: true,
      read: true,
      update: true
    },
    fields: input.fields,
    label: input.label,
    ownership: "organization",
    policy: input.policy,
    permissions: {},
    pluralLabel: pluralizeLabel(input.label),
    relations: input.relations ?? [],
    resource: input.resourceId,
    timestamps: {
      createdAtField: "createdAt",
      enabled: true,
      updatedAtField: "updatedAt"
    },
    ui: {
      createPage: false,
      detailPage: false,
      editPage: false,
      listPage: false,
      nav: false,
      navLabel: pluralizeLabel(input.label)
    }
  });
}

function readProductId(value: string) {
  if (!/^[a-z][a-z0-9-]*$/.test(value)) {
    throw new Error("Generated product ids must be lowercase kebab-case.");
  }

  return value;
}

function readNonEmptyString(value: unknown, field: string) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`Generated product spec field '${field}' must be a non-empty string.`);
  }

  return value.trim();
}

function readOptionalNonEmptyString(value: unknown, field: string) {
  if (value === undefined) {
    return undefined;
  }

  return readNonEmptyString(value, field);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function singularizeProductId(productId: string) {
  if (productId.endsWith("ies")) {
    return `${productId.slice(0, -3)}y`;
  }

  if (productId.endsWith("s")) {
    return productId.slice(0, -1);
  }

  return productId;
}

function pluralizeLabel(value: string) {
  if (value.endsWith("y")) {
    return `${value.slice(0, -1)}ies`;
  }

  if (value.endsWith("s")) {
    return `${value}es`;
  }

  return `${value}s`;
}

function pluralizePathSegment(value: string) {
  if (value.endsWith("y")) {
    return `${value.slice(0, -1)}ies`;
  }

  if (value.endsWith("s")) {
    return `${value}es`;
  }

  return `${value}s`;
}

function toKebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function toTitleCase(value: string) {
  return toKebabCase(value)
    .split("-")
    .filter((segment) => segment.length > 0)
    .map((segment) => segment[0]!.toUpperCase() + segment.slice(1))
    .join(" ");
}
